👌 IMPROVE: Add issue management to deployment pipeline

diff --git a/packages/process-cloudhub1v2/action.yml b/packages/process-cloudhub1v2/action.yml
--- a/packages/process-cloudhub1v2/action.yml
+++ b/packages/process-cloudhub1v2/action.yml
@@ -52,9 +52,9 @@ runs:
       # - cicd_connectedapp_clientid
       # - cicd_connectedapp_secret
 
-      #echo "outcome=failure" >> $GITHUB_OUTPUT
-      echo "outcome=success" >> $GITHUB_OUTPUT
-      exit 0
+      echo "outcome=failure" >> $GITHUB_OUTPUT
+      #echo "outcome=success" >> $GITHUB_OUTPUT
+      exit 1
 
       echo "Assigning variables to the script"
       deploymentenvironment="${{ inputs.deployment-env }}"
