🤖 TEST: Build pipeline with dynamic environments

diff --git a/.github/workflows/mule-build.yml b/.github/workflows/mule-build.yml
--- a/.github/workflows/mule-build.yml
+++ b/.github/workflows/mule-build.yml
@@ -99,10 +99,34 @@ jobs:
               }
             }
 
-      - name: Get global configuration
+      - name: Get service configuration
         uses: btfacrm/common-devops/packages/configuration-servicev2@main
         with:
           environment: build
+      
+      - name: Verify if the github tag exists
+        if: "!contains(env.service_version, 'snapshot')"
+        shell: bash
+        run: |
+          echo " "
+          echo "***********************************************"
+          echo "Verify if github tag exists "
+          echo "***********************************************"
+          echo " "
+
+          tag_exist=$(git tag $service_version)
+          if [ "$tag_exist" != "" ] ; then
+            echo "  Error, the tag already exists in Github; bump up the application version in the POM file"
+            exit 1
+          else
+            echo "  Create tag $service_version for the respository"
+          fi
+          
+      - name: Install Java JDK for Mulesoft Applications
+        uses: btfacrm/common-devops/packages/install-java@main
+        with:
+          github-configurations-accesstoken: $github_admintasks_accesstoken
+          default-settings-xml: $configurations_settings
 
       - id: issue-create
         name: Create a deployment issue
